server:
  port: 8011
  contextPath: /SpringBootFlyway

spring:
  application:
    name: SpringBootFlyway   
  datasource:
    initialize: true
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FLYWAY_DB
    password: Db12345
  
  jpa:
    hibernate :
     ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle10gDialect
    
flyway:
   enabled: true
   url: jdbc:oracle:thin:@localhost:1521:xe
   baselineOnMigrate : true       
   
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registerWithEureka: true
    fetchRegistry: false
 
  

  
