server:
  port: 8012
  contextPath: /SpringBootEnvers
  
spring:    
  application:
    name: SpringBootEnvers   #current service name to be used by the eureka server
  datasource:
    initialize: true
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ENVERS_FLYWAY_DB
    password: Db12345
  
  jpa:
    show-sql: true
    hibernate :
     ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle10gDialect
    
flyway:
   enabled: true
   url: jdbc:oracle:thin:@localhost:1521:xe
   baselineOnMigrate : true       
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registerWithEureka: true
    fetchRegistry: false
 
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
 
logging:
  level:
    com.example.howtodoinjava: DEBUG
  
